export const SUGGESTED_MODERATION_KEYWORDS: Record<string, string[]> = {
  selfHarm: [
    "kill myself",
    "killing myself",
    "end my life",
    "end it all",
    "want to die",
    "wanna die",
    "wish i was dead",
    "wish i were dead",
    "better off dead",
    "suicid*",
    "self harm",
    "selfharm",
    "cutting myself",
    "cut myself",
    "hurt myself",
    "no reason to live",
    "dont want to live",
    "hang myself",
    "hanging myself",
    "overdose",
    "sleeping pills",
    "rat poison",
    "atmahatya",
    "aatmahatya",
    "khudkushi",
    "marna chahta",
    "marna chahti",
    "mar jaunga",
    "mar jaungi",
    "jeena nahi",
    "chachipota*",
    "chanipota*",
    "chachipovali",
    "chanipovali",
    "आत्महत्या",
    "खुदकुशी",
    "मरना चाहता",
    "ఆత్మహత్య",
    "చచ్చిపో*",
    "చనిపో*",
  ],
  childSafety: [
    "underage",
    "under age",
    "minor girl",
    "minor boy",
    "child porn",
    "childporn",
    "cp links",
    "jailbait",
    "loli*",
    "pedo*",
    "paedo*",
    "age is just a number",
    "12 year old",
    "13 year old",
    "14 year old",
    "15 year old",
    "16 year old",
    "17 year old",
    "13yo",
    "14yo",
    "15yo",
    "16yo",
    "17yo",
    "schoolgirl",
    "dont tell your parents",
    "our little secret",
    "meet me alone",
    "grooming",
  ],
  violence: [
    "i will kill",
    "ill kill you",
    "going to kill",
    "gonna kill",
    "kill you",
    "kill him",
    "kill her",
    "kill them",
    "murder*",
    "rape*",
    "rapist*",
    "acid attack",
    "throw acid",
    "stab you",
    "stab him",
    "stab her",
    "stabbed",
    "shoot you",
    "shoot him",
    "shoot her",
    "bomb",
    "bombs",
    "bomb threat",
    "blow up",
    "beat you up",
    "lynch*",
    "behead*",
    "mass shooting",
    "school shooting",
    "terror attack",
    "jaan se maar*",
    "maar dalunga",
    "maar dunga",
    "champesta*",
    "champestha*",
    "champuta*",
    "champutha*",
    "narikesta*",
  ],
  harassment: [
    "kys",
    "kill yourself",
    "go die",
    "hope you die",
    "you should die",
    "die bitch",
    "slut",
    "whore",
    "nigger",
    "nigga",
    "faggot*",
    "tranny",
    "retard*",
    "chamar",
    "bhangi",
    "katua",
  ],
  personalInfo: [
    "my number",
    "my no is",
    "call me on",
    "call me at",
    "whatsapp me",
    "text me on",
    "dm me",
    "snap me",
    "my snap",
    "my insta",
    "insta id",
    "instagram id",
    "my ig",
    "telegram me",
    "home address",
    "my address",
    "aadhaar",
    "aadhar",
    "pan card",
    "upi id",
    "otp",
    "+91",
    "@gmail.com",
    "@yahoo.",
    "@outlook.",
    "wa.me/",
    "t.me/",
  ],
  drugs: [
    "buy weed",
    "weed for sale",
    "ganja",
    "charas",
    "maal chahiye",
    "mdma",
    "ecstasy",
    "cocaine",
    "coke for sale",
    "lsd",
    "heroin",
    "meth",
    "brown sugar",
    "mephedrone",
    "party drugs",
    "drugs for sale",
    "drug dealer",
  ],
  sexual: [
    "porn*",
    "nude*",
    "send pics",
    "sexting",
    "sex chat",
    "sexchat",
    "sex video*",
    "horny",
    "hookup",
    "escort*",
    "call girl*",
    "onlyfans",
    "xxx",
    "dick pic*",
    "nangi",
    "chudai",
  ],
  scams: [
    "earn money",
    "earn daily",
    "work from home",
    "investment plan",
    "double your money",
    "guaranteed returns",
    "crypto",
    "bitcoin",
    "forex",
    "trading tips",
    "betting tips",
    "satta",
    "matka",
    "instant loan",
    "loan app",
    "click here",
    "link in bio",
    "bit.ly",
    "tinyurl",
    "http://",
    "https://",
    "www.",
  ],
  abuse: [
    "fuck you",
    "motherfucker",
    "madarchod",
    "maderchod",
    "bhenchod",
    "behenchod",
    "bhosdi*",
    "chutiya",
    "chutiye",
    "gandu",
    "randi",
    "harami",
    "lavda",
    "lauda",
    "lanja*",
    "puku",
    "modda",
    "dengu",
    "dengey",
    "kojja",
    "punda",
    "thevdiya",
  ],
};

export const SUGGESTED_MODERATION_KEYWORD_LIST: string[] = Array.from(
  new Set(Object.values(SUGGESTED_MODERATION_KEYWORDS).flat()),
);
